const API=location.origin;
const state={locale:localStorage.getItem('ci_locale')||'zh',theme:localStorage.getItem('ci_theme')||'light',data:{},cart:JSON.parse(localStorage.getItem('ci_cart')||'[]'),category:null,environment:null,taskId:null,eventSource:null,eventCursor:0,logs:[]};
const $=id=>document.getElementById(id);
const lang={
  zh:{title:'Python-Package-Installer-for-Windows',subtitle:'V0.7.5 · Windows Python 可视化安装器',windows:'仅 Windows：本地 Agent 仅支持 Windows 10 / 11。',intro:'选择库后由本地 Agent 创建虚拟环境并安全执行 pip 安装。',env:'Python 环境',checking:'正在检测...',connected:'Agent 已连接',disconnected:'Agent 不可用',noPython:'Python 或 pip 不可用',python:'Python',pip:'pip',path:'路径',system:'系统',solutions:'建议解决方案',packages:'选择包',search:'搜索包名或描述',cart:'安装清单',custom:'单个 PyPI 包需求，例如 requests==2.31.0',add:'加入',added:'已加入',remove:'移除',empty:'暂无包',invalid:'仅允许一个安全的 PyPI 包需求。',catalogSummary:'{categories} 个分类 · {packages} 个库',catalogLoadFailed:'包目录加载失败',settings:'安装设置',newVenv:'创建或复用独立虚拟环境（推荐）',currentPython:'使用当前检测到的 Python',existingVenv:'使用工作区内已有 .venv',workspace:'工作区名称',pythonCommand:'Python 命令',mirror:'镜像源',mirrorOfficial:'官方 PyPI',start:'开始安装',install:'安装进度',back:'返回选包',queued:'任务已排队',preparing:'正在准备环境...',installing:'正在安装',completed:'安装完成',completedErrors:'安装完成，存在失败项',failed:'任务失败',success:'成功',failure:'失败',waiting:'等待中',current:'当前',progress:'进度',error:'错误',logs:'实时安装日志',live:'实时连接',reconnecting:'正在重连',cannotStart:'请先启动 Agent，并确认 Python 与 pip 可用。',emptyCart:'请先至少加入一个包。',requestFailed:'创建安装任务失败：{error}',importRequirements:'导入 requirements.txt',exportRequirements:'导出 requirements.txt',importConfig:'导入配置',exportConfig:'导出配置',requirementsImported:'已导入 {accepted} 个包，跳过 {rejected} 条无效或重复项。',configImported:'已恢复 {count} 个包和安装设置。',fileReadFailed:'读取文件失败：{error}',invalidConfig:'配置文件无效或不受支持。',presetTitle:'AI 开发预设',presetApply:'加入预设',presetApplied:'已加入 {count} 个预设包。',presetAI:'AI 基础环境',presetML:'机器学习',presetLLM:'LLM 开发',presetData:'数据分析',mirrorSpeed:'镜像测速',testMirrors:'测速并推荐',testingMirrors:'正在测速...',mirrorRecommended:'已推荐 {name}（{latency} ms）',mirrorUnavailable:'没有可用的镜像。',mirrorApply:'使用',mirrorOfficial:'官方 PyPI',phase:'V0.7.5：AI 环境预设与镜像测速。'},
  en:{title:'Python-Package-Installer-for-Windows',subtitle:'V0.7.5 · Windows Python Visual Installer',windows:'Windows only: the local Agent supports Windows 10 / 11 only.',intro:'Choose packages, then the local Agent creates an environment and safely runs pip.',env:'Python environment',checking:'Checking...',connected:'Agent connected',disconnected:'Agent unavailable',noPython:'Python or pip is unavailable',python:'Python',pip:'pip',path:'Path',system:'System',solutions:'Suggested fixes',packages:'Choose packages',search:'Search package or description',cart:'Install list',custom:'One PyPI requirement, e.g. requests==2.31.0',add:'Add',added:'Added',remove:'Remove',empty:'No packages',invalid:'Only one safe PyPI requirement is allowed.',catalogSummary:'{categories} categories · {packages} packages',catalogLoadFailed:'Package catalog failed to load',settings:'Install settings',newVenv:'Create or reuse an isolated virtual environment (recommended)',currentPython:'Use the detected Python',existingVenv:'Use an existing workspace .venv',workspace:'Workspace name',pythonCommand:'Python command',mirror:'Package index',mirrorOfficial:'Official PyPI',start:'Start installation',install:'Installation progress',back:'Back to packages',queued:'Task queued',preparing:'Preparing environment...',installing:'Installing',completed:'Installation complete',completedErrors:'Installation completed with failures',failed:'Task failed',success:'Success',failure:'Failed',waiting:'Waiting',current:'Current',progress:'Progress',error:'Error',logs:'Live installation log',live:'Live connection',reconnecting:'Reconnecting',cannotStart:'Start the Agent and confirm Python and pip are available.',emptyCart:'Add at least one package first.',requestFailed:'Could not create installation task: {error}',importRequirements:'Import requirements.txt',exportRequirements:'Export requirements.txt',importConfig:'Import configuration',exportConfig:'Export configuration',requirementsImported:'Imported {accepted} packages; skipped {rejected} invalid or duplicate entries.',configImported:'Restored {count} packages and installation settings.',fileReadFailed:'Could not read file: {error}',invalidConfig:'The configuration file is invalid or unsupported.',phase:'V0.7.5: requirements.txt and click-install.json import and export.'}
};
Object.assign(lang.zh,{subtitle:'V0.7.5 · Windows Python 可视化安装器',presetTitle:'AI 开发预设',presetApply:'加入预设',presetApplied:'已加入 {count} 个预设包。',presetAI:'AI 基础环境',presetML:'机器学习',presetLLM:'LLM 开发',presetData:'数据分析',mirrorSpeed:'镜像测速',testMirrors:'测速并推荐',testingMirrors:'正在测速...',mirrorRecommended:'已推荐 {name}（{latency} ms）',mirrorUnavailable:'没有可用的镜像。',mirrorApply:'使用'});
Object.assign(lang.en,{subtitle:'V0.7.5 · Windows Python Visual Installer',presetTitle:'AI development presets',presetApply:'Add preset',presetApplied:'Added {count} preset packages.',presetAI:'AI basics',presetML:'Machine learning',presetLLM:'LLM development',presetData:'Data analysis',mirrorSpeed:'Mirror benchmark',testMirrors:'Benchmark and recommend',testingMirrors:'Benchmarking...',mirrorRecommended:'Recommended {name} ({latency} ms)',mirrorUnavailable:'No package index is available.',mirrorApply:'Use'});
const PRESETS={ai:{packages:['numpy','pandas','jupyter'],label:'presetAI'},ml:{packages:['numpy','scikit-learn','xgboost'],label:'presetML'},llm:{packages:['torch','transformers','accelerate','datasets'],label:'presetLLM'},data:{packages:['numpy','pandas','matplotlib','jupyterlab'],label:'presetData'}};
function t(key,vars={}){return Object.entries(vars).reduce((text,[name,value])=>text.replaceAll('{'+name+'}',value),lang[state.locale][key]||key)}
function esc(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function save(){localStorage.setItem('ci_cart',JSON.stringify(state.cart))}
function toast(message){$('toast').textContent=message;$('toast').classList.add('on');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('on'),2200)}
function validRequirement(value){const name='[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?',extra='[A-Za-z0-9]+(?:[A-Za-z0-9._-]*[A-Za-z0-9])?',version='[A-Za-z0-9][A-Za-z0-9.*+!._-]*';return new RegExp('^'+name+'(?:\\['+extra+'(?:,'+extra+')*\\])?(?:(?:===|==|!=|<=|>=|~=|<|>)'+version+')?$').test(value)}
function validWorkspace(value){return typeof value==='string'&&/^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/.test(value)}
function stats(){return {categories:Object.keys(state.data).length,packages:Object.values(state.data).reduce((total,items)=>total+items.length,0)}}
function staticText(){document.documentElement.lang=state.locale==='zh'?'zh-CN':'en';document.documentElement.dataset.theme=state.theme;document.title=t('title')+' V0.7.5';[['title','title'],['subtitle','subtitle'],['windowsOnly','windows'],['intro','intro'],['envTitle','env'],['packagesTitle','packages'],['cartTitle','cart'],['settingsTitle','settings'],['newVenvLabel','newVenv'],['currentPythonLabel','currentPython'],['existingVenvLabel','existingVenv'],['workspaceLabel','workspace'],['pythonCommandLabel','pythonCommand'],['mirrorLabel','mirror'],['presetTitle','presetTitle'],['mirrorSpeedTitle','mirrorSpeed'],['benchmarkMirrors','testMirrors'],['startInstall','start'],['installTitle','install'],['backBtn','back'],['liveLogTitle','logs'],['phaseNote','phase']].forEach(([id,key])=>$(id).textContent=t(key));$('search').placeholder=t('search');$('customRequirement').placeholder=t('custom');$('addCustom').textContent=t('add');$('importRequirements').textContent=t('importRequirements');$('exportRequirements').textContent=t('exportRequirements');$('importConfig').textContent=t('importConfig');$('exportConfig').textContent=t('exportConfig');$('langBtn').textContent=state.locale==='zh'?'EN':'中';$('mirror').options[0].textContent=t('mirrorOfficial');const summary=stats();$('catalogSummary').textContent=summary.categories?t('catalogSummary',summary):t('catalogLoadFailed');renderLogs();renderPresets()}
function renderCatalog(){const categories=Object.keys(state.data);if(!state.data[state.category])state.category=categories[0]||null;$('categories').innerHTML=categories.map(category=>'<div class="cat '+(category===state.category?'on':'')+'" data-cat="'+esc(category)+'"><span>'+esc(category)+'</span><small>'+state.data[category].length+'</small></div>').join('');$('categories').querySelectorAll('.cat').forEach(element=>element.onclick=()=>{state.category=element.dataset.cat;renderCatalog()});const query=$('search').value.trim().toLowerCase(),rows=query?Object.values(state.data).flat().filter(item=>(item[0]+' '+item[1]).toLowerCase().includes(query)):(state.data[state.category]||[]);$('packageList').innerHTML=rows.length?rows.map(([name,description])=>'<div class="package"><b>'+esc(name)+'</b><p>'+esc(description)+'</p><button class="btn '+(state.cart.includes(name)?'':'primary')+'" data-p="'+esc(name)+'">'+t(state.cart.includes(name)?'added':'add')+'</button></div>').join(''):'<p>'+t('empty')+'</p>';$('packageList').querySelectorAll('[data-p]').forEach(button=>button.onclick=()=>add(button.dataset.p))}
function renderCart(){$('cartList').innerHTML=state.cart.length?state.cart.map(name=>'<div class="cart-item"><span>'+esc(name)+'</span><button class="remove" data-r="'+esc(name)+'">× '+t('remove')+'</button></div>').join(''):'<p class="footer">'+t('empty')+'</p>';$('cartList').querySelectorAll('[data-r]').forEach(button=>button.onclick=()=>{state.cart=state.cart.filter(name=>name!==button.dataset.r);save();renderCart();renderCatalog()})}
function renderPresets(){$('presetList').innerHTML=Object.entries(PRESETS).map(([id,preset])=>'<article class="preset"><div><b>'+t(preset.label)+'</b><small>'+esc(preset.packages.join(' · '))+'</small></div><button class="btn" data-preset="'+id+'">'+t('presetApply')+'</button></article>').join('');$('presetList').querySelectorAll('[data-preset]').forEach(button=>button.onclick=()=>applyPreset(button.dataset.preset))}
function applyPreset(id){const preset=PRESETS[id];if(!preset)return;const before=state.cart.length;preset.packages.forEach(add);const added=state.cart.length-before;toast(t('presetApplied',{count:added}));}
function renderMirrorResults(results=[],recommended=''){const root=$('mirrorResults');if(!results.length){root.textContent='';return}root.innerHTML=results.map(item=>{const name=item.mirror===''?t('mirrorOfficial'):item.label;const value=item.available?item.latency_ms+' ms':t('mirrorUnavailable');return '<article class="mirror-result '+(!item.available?'unavailable ':'')+(item.mirror===recommended?'recommended':'')+'"><span>'+esc(name)+'</span><span class="latency">'+esc(value)+'</span>'+(item.available?'<button class="btn" data-mirror="'+esc(item.mirror)+'">'+t('mirrorApply')+'</button>':'<span></span>')+'</article>'}).join('');root.querySelectorAll('[data-mirror]').forEach(button=>button.onclick=()=>applyMirror(button.dataset.mirror))}
function applyMirror(value){$('mirror').value=value;localStorage.setItem('ci_mirror',value)}
async function benchmarkMirrors(){const button=$('benchmarkMirrors');button.disabled=true;button.textContent=t('testingMirrors');try{const response=await fetch(API+'/api/mirrors/benchmark',{cache:'no-store'}),payload=await response.json();if(!response.ok||!payload.ok)throw Error(payload.error||response.status);renderMirrorResults(payload.results,payload.recommended_mirror);if(payload.recommended_mirror!==undefined){applyMirror(payload.recommended_mirror);const item=payload.results.find(result=>result.mirror===payload.recommended_mirror);if(item)toast(t('mirrorRecommended',{name:item.mirror===''?t('mirrorOfficial'):item.label,latency:item.latency_ms}))}}catch(error){$('mirrorResults').textContent=t('mirrorUnavailable')}finally{button.disabled=false;button.textContent=t('testMirrors')}}
function add(name){if(!state.cart.includes(name)){state.cart.push(name);save();renderCart();renderCatalog()}}
function metric(label,value){return '<div class="metric"><small>'+esc(label)+'</small><b>'+esc(value||'—')+'</b></div>'}
async function checkEnvironment(command='python'){const badge=$('connection');badge.className='badge';badge.textContent=t('checking');try{const response=await fetch(API+'/api/environment?python='+encodeURIComponent(command),{cache:'no-store'}),payload=await response.json(),environment=payload.environment;if(!environment)throw Error();state.environment=environment;badge.className='badge '+(payload.ok?'ok':'error');badge.textContent=payload.ok?t('connected'):t('noPython');$('envContent').innerHTML=metric(t('python'),environment.version)+metric(t('pip'),environment.pip_version)+metric(t('path'),environment.executable)+metric(t('system'),environment.platform+' · '+environment.architecture);$('solutions').innerHTML=environment.solutions?.length?'<b>'+t('solutions')+'</b><ul>'+environment.solutions.map(item=>'<li>'+esc(item)+'</li>').join('')+'</ul>':''}catch(error){state.environment=null;badge.className='badge error';badge.textContent=t('disconnected');$('envContent').innerHTML='';$('solutions').textContent='Run: python run_agent.py'}}
function closeEvents(){if(state.eventSource){state.eventSource.close();state.eventSource=null}}
function showInstall(){closeEvents();$('catalogPage').classList.add('hidden');$('installPage').classList.remove('hidden')}
function showCatalog(){closeEvents();$('installPage').classList.add('hidden');$('catalogPage').classList.remove('hidden')}
function statusKey(status){return {queued:'queued',preparing:'preparing',installing:'installing',completed:'completed',completed_with_errors:'completedErrors',failed:'failed'}[status]||status}
function renderTask(task){const percent=task.total?Math.round(task.completed/task.total*100):0;$('taskSummary').innerHTML='<div class="task-status"><b>'+t(statusKey(task.status))+'</b><span>'+t('progress')+': '+task.completed+' / '+task.total+' ('+percent+'%)</span></div><div class="progress-track" aria-label="'+t('progress')+'"><span style="width:'+percent+'%"></span></div><div class="task-metrics"><span>'+t('success')+': '+task.success_count+'</span><span>'+t('failure')+': '+task.failed_count+'</span><span>'+t('current')+': '+esc(task.current_package||'—')+'</span></div>';$('taskError').textContent=task.error?t('error')+': '+task.error:'';$('taskPackages').innerHTML=task.packages.map(item=>'<article class="task-package '+item.status+'"><b>'+({success:'✓',failed:'×',installing:'⬇',waiting:'○'}[item.status]||'○')+' '+esc(item.name)+'</b><span>'+t(item.status==='success'?'success':item.status==='failed'?'failure':item.status==='installing'?'installing':'waiting')+(item.return_code!==null?' · '+item.return_code:'')+'</span>'+(item.stderr?'<pre>'+esc(item.stderr)+'</pre>':'')+'</article>').join('')}
function renderLogs(){const view=$('liveLog');if(!view)return;view.innerHTML=state.logs.map(entry=>'<div class="log-line '+esc(entry.level||'info')+'"><time>'+esc(new Date(entry.time).toLocaleTimeString())+'</time><span>'+esc(entry.package?entry.package+' · ':'')+esc(entry.message)+'</span></div>').join('');view.scrollTop=view.scrollHeight}
function appendLog(entry){if(entry.id&&entry.id<=state.eventCursor)return;state.eventCursor=Math.max(state.eventCursor,entry.id||0);state.logs.push(entry);if(state.logs.length>500)state.logs.splice(0,state.logs.length-500);renderLogs()}
async function loadTask(){const response=await fetch(API+'/api/tasks/'+encodeURIComponent(state.taskId),{cache:'no-store'}),payload=await response.json();if(!payload.ok)throw Error(payload.error);renderTask(payload.task);return payload.task}
function isFinished(task){return ['completed','completed_with_errors','failed'].includes(task.status)}
function finishStream(task){renderTask(task);const badge=$('liveStatus');badge.className='badge';badge.textContent=t(statusKey(task.status));closeEvents()}
function connectEvents(){closeEvents();const badge=$('liveStatus');badge.className='badge ok';badge.textContent=t('live');const source=new EventSource(API+'/api/tasks/'+encodeURIComponent(state.taskId)+'/events?after='+state.eventCursor);state.eventSource=source;source.addEventListener('log',event=>appendLog(JSON.parse(event.data)));source.addEventListener('task',event=>{const task=JSON.parse(event.data);if(isFinished(task))finishStream(task);else renderTask(task)});source.onerror=async()=>{if(source!==state.eventSource)return;badge.className='badge error';badge.textContent=t('reconnecting');try{const task=await loadTask();if(isFinished(task))finishStream(task)}catch(error){$('taskError').textContent=t('error')+': '+error.message}}}
async function startInstall(){if(!state.environment?.available||!state.environment?.pip_available)return toast(t('cannotStart'));if(!state.cart.length)return toast(t('emptyCart'));const mode=document.querySelector('input[name="environmentMode"]:checked').value,workspace=$('workspace').value.trim(),mirror=$('mirror').value,pythonCommand=$('pythonCommand').value;try{const response=await fetch(API+'/api/install',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({packages:state.cart,environment_mode:mode,workspace,mirror,python_command:pythonCommand})}),payload=await response.json();if(!response.ok||!payload.ok)throw Error(payload.error||response.status);state.taskId=payload.task_id;state.eventCursor=0;state.logs=[];showInstall();const task=await loadTask();renderTask(task);connectEvents()}catch(error){toast(t('requestFailed',{error:error.message}))}}
function download(name,content,type){const blob=new Blob([content],{type:type||'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function selectedMode(){return document.querySelector('input[name="environmentMode"]:checked').value}
function reportImport(message){$('importResult').textContent=message}
function addImportedRequirements(text){let accepted=0,rejected=0;for(const raw of text.replace(/^\uFEFF/,'').split(/\r?\n/)){const value=raw.trim();if(!value||value.startsWith('#'))continue;if(!validRequirement(value)||state.cart.includes(value)||state.cart.length>=100){rejected++;continue}state.cart.push(value);accepted++}save();renderCart();renderCatalog();reportImport(t('requirementsImported',{accepted,rejected}))}
function exportRequirements(){if(!state.cart.length)return toast(t('emptyCart'));download('requirements.txt',state.cart.join('\r\n')+'\r\n')}
function exportConfig(){const config={format:'Python-Package-Installer-for-Windows',version:'0.7.5',windows_only:true,environment:{mode:selectedMode(),workspace:$('workspace').value.trim(),python_command:$('pythonCommand').value,mirror:$('mirror').value},packages:[...state.cart]};download('Python-Package-Installer-for-Windows.json',JSON.stringify(config,null,2)+'\n','application/json;charset=utf-8')}
function importConfig(text){let config;try{config=JSON.parse(text.replace(/^\uFEFF/,''))}catch(error){return toast(t('invalidConfig'))}const env=config&&config.environment,packages=config&&config.packages;if(!config||config.format!=='Python-Package-Installer-for-Windows'||config.version!=='0.7.5'||config.windows_only!==true||!Array.isArray(packages)||packages.length>100||!env||!['new_venv','current_python','existing_venv'].includes(env.mode)||!['python','py','python3'].includes(env.python_command)||!validWorkspace(env.workspace)||!['','https://pypi.tuna.tsinghua.edu.cn/simple','https://mirrors.aliyun.com/pypi/simple/','https://pypi.mirrors.ustc.edu.cn/simple/','https://mirrors.huaweicloud.com/repository/pypi/simple/'].includes(env.mirror)){return toast(t('invalidConfig'))}const clean=[];for(const item of packages){if(typeof item==='string'&&validRequirement(item)&&!clean.includes(item))clean.push(item)}if(clean.length!==packages.length)return toast(t('invalidConfig'));state.cart=clean;$('workspace').value=env.workspace;$('pythonCommand').value=env.python_command;$('mirror').value=env.mirror;document.querySelector('input[name="environmentMode"][value="'+env.mode+'"]').checked=true;save();localStorage.setItem('ci_python_command',env.python_command);localStorage.setItem('ci_mirror',env.mirror);renderCart();renderCatalog();checkEnvironment(env.python_command);reportImport(t('configImported',{count:clean.length}))}
async function readSelectedFile(input,handler){const file=input.files&&input.files[0];input.value='';if(!file)return;try{handler(await file.text())}catch(error){toast(t('fileReadFailed',{error:error.message}))}}
$('langBtn').onclick=()=>{state.locale=state.locale==='zh'?'en':'zh';localStorage.setItem('ci_locale',state.locale);staticText();renderCatalog();renderCart();checkEnvironment($('pythonCommand').value)};
$('themeBtn').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';localStorage.setItem('ci_theme',state.theme);staticText()};
$('refreshBtn').onclick=()=>checkEnvironment($('pythonCommand').value);
$('pythonCommand').onchange=()=>{localStorage.setItem('ci_python_command',$('pythonCommand').value);checkEnvironment($('pythonCommand').value)};
$('mirror').onchange=()=>localStorage.setItem('ci_mirror',$('mirror').value);
$('search').oninput=renderCatalog;
$('addCustom').onclick=()=>{const value=$('customRequirement').value.trim();if(!validRequirement(value))return toast(t('invalid'));add(value);$('customRequirement').value=''};
$('customRequirement').onkeydown=event=>{if(event.key==='Enter')$('addCustom').click()};
$('importRequirements').onclick=()=>$('requirementsFile').click();$('exportRequirements').onclick=exportRequirements;$('importConfig').onclick=()=>$('configFile').click();$('exportConfig').onclick=exportConfig;$('requirementsFile').onchange=()=>readSelectedFile($('requirementsFile'),addImportedRequirements);$('configFile').onchange=()=>readSelectedFile($('configFile'),importConfig);
$('benchmarkMirrors').onclick=benchmarkMirrors;$('startInstall').onclick=startInstall;$('backBtn').onclick=showCatalog;
(async()=>{$('pythonCommand').value=localStorage.getItem('ci_python_command')||'python';$('mirror').value=localStorage.getItem('ci_mirror')||'';staticText();try{const response=await fetch(API+'/packages.json',{cache:'no-store'});if(!response.ok)throw Error();state.data=await response.json()}catch(error){console.error(error)}staticText();renderCatalog();renderCart();checkEnvironment($('pythonCommand').value)})();
